load("@rules_swift//swift:swift_test.bzl", "swift_test")

swift_test(
    name = "KeyCodeTests",
    srcs = ["KeyCodeTests.swift"],
    deps = [
        "//Sources/DivvyClick:core",
    ],
)

swift_test(
    name = "KeyMapTests",
    srcs = [
        "KeyMapTests.swift",
        "MockCursorEngine.swift",
        "MockScreenProvider.swift",
    ],
    deps = [
        "//Sources/DivvyClick:coordination",
        "//Sources/DivvyClick:core",
        "//Sources/DivvyClick:engine",
        "//Sources/DivvyClick:layouts",
    ],
)

swift_test(
    name = "NavigationCoordinatorTests",
    srcs = [
        "MockCursorEngine.swift",
        "MockScreenProvider.swift",
        "NavigationCoordinatorTests.swift",
    ],
    deps = [
        "//Sources/DivvyClick:coordination",
        "//Sources/DivvyClick:core",
        "//Sources/DivvyClick:engine",
    ],
)

swift_test(
    name = "NavigationEngineTests",
    srcs = [
        "MockScreenProvider.swift",
        "NavigationEngineTests.swift",
    ],
    deps = [
        "//Sources/DivvyClick:core",
        "//Sources/DivvyClick:engine",
        "//Sources/DivvyClick:layouts",
    ],
)

swift_test(
    name = "HotkeyManagerTests",
    srcs = [
        "HotkeyManagerTests.swift",
        "MockCursorEngine.swift",
        "MockScreenProvider.swift",
    ],
    deps = [
        "//Sources/DivvyClick:coordination",
        "//Sources/DivvyClick:core",
        "//Sources/DivvyClick:engine",
        "//Sources/DivvyClick:ui",
    ],
)
