#!/bin/bash
set -Eeuo pipefail

# When run via "bazel run //:package_dmg", $1 is the resolved path 
# to the zip file generated by the :DivvyClick target.
BUILD_OUTPUT="$1"

if [ -z "$BUILD_OUTPUT" ]; then
    echo "Error: Must provide the path to DivvyClick.zip as an argument."
    echo "Usage: bazel run //:package_dmg"
    exit 1
fi

if [ ! -f "$BUILD_OUTPUT" ]; then
    echo "Error: Could not find build output at $BUILD_OUTPUT"
    exit 1
fi

# If running via "bazel run", output to the workspace root directory.
# Otherwise, output to the current directory.
OUTPUT_DIR="${BUILD_WORKSPACE_DIRECTORY:-$PWD}"
DMG_NAME="$OUTPUT_DIR/bazel-bin/DivvyClick.dmg"

echo "Packaging $DMG_NAME from $BUILD_OUTPUT..."

# Create a temporary staging directory
WORK_DIR=$(mktemp -d "/tmp/divvyclick-dmg.XXXXXX")
# Ensure the temp directory is cleaned up on exit
trap 'rm -rf "$WORK_DIR"' EXIT

# Unzip the app bundle into the staging directory
unzip -q -d "$WORK_DIR" "$BUILD_OUTPUT"

# Create a temporary empty read/write disk image
TEMP_DMG="$WORK_DIR/temp.dmg"
hdiutil create -size 50m -fs HFS+ -volname 'DivvyClick' -type UDIF "$TEMP_DMG"

# Mount the image
MOUNT_DIR="$WORK_DIR/mount"
mkdir -p "$MOUNT_DIR"
# Use -nobrowse to prevent Finder popups
hdiutil attach "$TEMP_DMG" -mountpoint "$MOUNT_DIR" -nobrowse -quiet

# Copy the application into the mounted image
cp -R "$WORK_DIR/DivvyClick.app" "$MOUNT_DIR/"

# Create the symlink directly on the mounted volume
ln -s /Applications "$MOUNT_DIR/Applications"

# Sync to ensure all data is written
sync

# Unmount the image cleanly (retry with force if busy)
hdiutil detach "$MOUNT_DIR" -quiet || { sleep 2 && hdiutil detach "$MOUNT_DIR" -force -quiet; }

# Remove any existing DMG with the same name
if [ -f "$DMG_NAME" ]; then
    rm "$DMG_NAME"
fi

# Convert the temporary read/write image to a final compressed, read-only DMG
hdiutil convert "$TEMP_DMG" -format UDZO -o "$DMG_NAME"

echo "Successfully created $DMG_NAME for distribution!"
